### PR TITLE
Improve the yacr2 workaround to avoid duplicating structs and typedefs in multiple files.

### PR DESCRIPTION
**Pull request by mattmccutchen-cci**
It's conceivable that the duplication could cause incorrect behavior since 3C currently matches structs and typedefs by source location (https://github.com/correctcomputation/checkedc-clang/issues/499).

@john-h-kastner After I approved #19, I thought I should take a closer look at what it was actually doing to the yacr2 code, and I discovered this problem.  I ran the sed scripts locally on yacr2 and the results looked like what I intended, but I haven't tried a build yet.  If you are OK with the approach, contingent on the workflow working as intended, then I'll try running the workflow.

### CODE REVIEW

**Comment by john-h-kastner** [comment]
I'm having trouble building yacr2 with this change (before any conversion). 
```
In file included from assign.c:21:
assign_code.h:2:12: error: conflicting types for ‘costMatrix’
    2 | long * *   costMatrix;
      |            ^~~~~~~~~~
In file included from assign.c:20:
assign.h:63:19: note: previous declaration of ‘costMatrix’ was here
   63 | extern ulong * *  costMatrix;

```

**Comment by mattmccutchen-cci** [comment]
Yuck, yacr2 has contradictory types; I guess we were lucky that 3C doesn't care if the base types don't match.  Sorry to put you to the trouble.  I can see whether it's straightforward to patch that or, if not, maybe I'll deprioritize this PR.

**Comment by mattmccutchen-cci** [comment]
Looks like that was the only type conflict.  Try now?

**Review by john-h-kastner — APPROVED** [review]
Works now.

**Comment by mattmccutchen-cci** [comment]
[Workflow run](https://github.com/correctcomputation/actions/actions/runs/712657755) looks OK (note, that run did not have the recently merged icecast fix).

**Pull request merged**
